### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by ilgrandeanonimo** [kcuzner/led-watch#2]
Can you create a boot loader for Debian?
Or how can I?

**Comment by kcuzner** [comment]
I'm not sure what you are asking? The project you have commented on is a bare-metal microcontroller-based project and the bootloader here is a structure which facilitates choosing which of two binaries to run. It is not able to, and cannot ever, boot Linux.

Bootloaders for operating systems like Linux are somewhat more complicated, but you can use projects like [Yocto](https://www.yoctoproject.org/) to get started. If you're trying to make a UEFI-compatible bootloader, I would suggest reading the [grub2](https://github.com/rhboot/grub2) source code (or perhaps just using grub directly).

I'm feeling generous, so I'll write you a book as an answer :).

You're going to have to get a lot more specific and do a lot more research, but here are some questions to help you get started:

 - What hardware are you developing for?
   - **Traditional motherboard, using a processor from AMD/Intel/etc**: Check out grub and UEFI, learn how they work. If you're interested in writing a BIOS, most companies hire out a vendor like [Phoenix Technologies](https://www.phoenix.com/) to write their BIOS's. Writing a BIOS is extraordinarily complex and not something you'll be able to do on your own until you learn a lot more, start a company, and sign a few NDAs with AMD and Intel.
   - **A microcontroller, like this project**: A "bootloader" for these systems is a small piece of software that runs before the actual application is run in order to decide which version to run. This is inherently linked to the concept of "firmware update" and providing a "fallback" for the case where a firmware update is interrupted by the power being shut off or a communications error.
     - Most microcontrollers cannot run Linux in the first place. They don't have an MMU or the required protections for an operating system like Linux to run correctly. You need an applications processor, such as an ARM Cortex-R82 or something more advanced. Many vendors, including Microchip Inc, ST, NXP/Freescale, and TI create Linux-capable microprocessors and will provide bootloaders for you.
 - Why do you need to write a bootloader?
   - If you need to write it so you can faciliate firmware update to a single-program microcontroller, than this repo should be able to help you get started.
   - If you don't know why you need a bootloader, then you probably don't need one.
     - Most PCs, including embedded ones like the Raspberry Pi, have a bootloader already built-in for you. Custom bootloaders are a big deal and very complex. One of those things where "if you're asking the question, you don't know what you don't know".
       - Unless the processor is super custom, you'll probably find a Debian distribution that'll run on this hardware.
     - Most microprocessors have a bootloader supplied by their vendor, if they even require a bootloader (many of them don't, especially if they've got integrated flash memory). Unless you have a company and are signing NDAs, you cannot write your own bootloader for these and you must use theirs.
       - If you can run Linux on the hardware, Debian is popular enough that you should be able to find it a distribution available for most reasonably popular platforms.
     - Most microcontrollers do not require a bootloader to function at all and many applications can get away with not having any sort of bootloader. You'll only need one if you're intending to support in-field firmware updates really.
       - Microcontrollers cannot run Linux.

The other thing is, you're asking specifically about "Debian", but not "Linux". This shows that you do not understand the difference between Linux and a Distribution. The question should be "Can you create a boot loader for Linux?". Debian is simply a collection of programs bundled around a slightly customized linux kernel. Bootloaders for Linux are never really distribution-specific. If you're wanting to run Debian specifically on some hardware, you need to be prepared to recompile every single program and package that comes with it for your specific processor (unless it's one of the [explicitly listed Ports here](https://www.debian.org/ports/)).
